package files.howtos

import utils.*
import Bundle.*, Tags.*

object InsertRetGenKeys extends HowToPage {

  override def pageSettings =
    super.pageSettings.withTitle("Insert returning generated keys")

  override def blogSettings =
    super.blogSettings.withSections(firstSection)

  val firstSection = Section(
    "How To Insert Returning Generated Keys?",
    frag(
      s"""
      This method inserts the rows and returns autogenerated keys (`AUTOINCREMENT`, `SERIAL` etc).
      ```scala
      def insertCustomer: Seq[Int] = ctx.run {
        sql"INSERT INTO customers(name) VALUES('my_customer')".insertReturningGenKeys[Int]()
      }
      ```

      ---

      There are also variations that return a single result, depending if you want an `Option[T]` or `T` (throws if no row returned):
      ```scala
      sql"SELECT ...".insertReturningGenKey[T]() : Option[T]
      sql"SELECT ...".insertReturningGenKey[T]() : T
      ```

      """.md
    )
  )
}
