
name: CI
on:
  push:
    branches: [master, main]
  pull_request:
jobs:
  test:
    name: test ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - run: ./mill -i squery.__.test
